adammck/terraform-inventory

README.md
cli.go
main.go
parser.go
parser_test.go

This change is admittedly overkill for just defining the state path.
However, this opens the door for additional configuration options 
to be defined in environment variables such as choosing the keys 
to match on for the "host" argument.

Patch to add support for environment variables

---

homebrew/terraform-inventory.rb

At the moment the ```brew install``` command in the README is downloading version 0.4, however the latest release is version 0.5.

Update homebrew script to download version 0.5

---

README.md
parser.go
parser_test.go

This patch adds support for VMware machines.  It's just a matter of adding the name of the IP address attribute, but I've included tests as well.

Add VMware support

---

README.md
cli.go
fixtures/example.tf
fixtures/example.tfstate
parser.go
parser_test.go

This is a little ugly, because the internal data structures weren't really designed for this. I didn't consider resources which use the `count` attribute to spawn multiple copies. But it works. When run against the updated [tfstate fixture](https://github.com/adammck/terraform-inventory/blob/counted_instances/fixtures/example.tfstate):
```
./terraform-inventory --list fixtures/example.tfstate | jq .
```
The output is:
```json
{
"web-aws": [
"52.7.58.202",
"52.91.51.56"
],
"web-aws.0": [
"52.7.58.202"
],
"web-aws.1": [
"52.91.51.56"
],
"web-cs": [
"10.2.1.5"
],
"web-cs.0": [
"10.2.1.5"
],
"web-do": [
"192.241.136.44"
],
"web-do.0": [
"192.241.136.44"
]
}
```
Note that resources are now accessible by their exact name, which includes the counter, and as a group by their base name, which does …

Add support for grouped count=n resources

---

README.md
resource.go

Added GCE support based on the terraform state file example below.
```
{
"version": 1,
"serial": 1,
"modules": [
{
"path": [
"root"
],
"outputs": {},
"resources": {}
},
{
"path": [
"root",
"gce-dc"
],
"outputs": {
"dbhost_ips": "1.1.1.1"
},
"resources": {
"google_compute_disk.dbcluster-lvm": {
"type": "google_compute_disk",
"primary": {
"id": "db-lvm-01",
"attributes": {
"id": "db-lvm-01",
"name": "db-lvm-01",
"self_link": "https://www.googleapis.com/compute/v1/projects",
"size": "20",
"type": "pd-ssd",
"zone": "europe-west1-b"
}
}
},
"google_compute_firewall.db-firewall-ext": {
"type": "google_compute_firewall",
"depends_on": [
"google_compute_network.db-network"
],
"primary": {
"id": "db-firewall-ext",
"attributes": {
"allow.#": "2",
"allow.1367131964.ports.#": "0", …
```

Added GCE support

---

resource.go

I am not sure that this PR is useful. But I need it. :-) 
For example, I want to use the terraform-inventory in a VPC.
$export TERRAFORM_INVENTORY_KEYNAME=private_ip
(go:terraform-inventory) anarch@booker ~/go/terraform-inventory/src/anarcher/terraform-inventory (master) 
$./terraform-inventory --list
{ "instance" : ["10.90.0.2"],"name_instance" : ["10.90.0.35"] }
Anyway,  I like the terraform-inventory. It's a good idea and very useful for me! :-)
Thanks,

Add ENV TERRAFORM_INVENTORY_KEYNAME to specify which IP to return

---

cli.go
main.go

I introduced the --inventory option which changes the output from the classic json format from --list to an output similar to Ansible host file.
The following configuration:
resource "digitalocean_droplet" "gamma" {
image = "centos-7-0-x64"
name = "terraform-inventory-1"
region = "nyc1"
size = "512mb"
ssh_keys = [862272]
}
resource "digitalocean_droplet" "zeta" {
image = "centos-7-0-x64"
name = "terraform-inventory-1"
region = "nyc1"
size = "512mb"
ssh_keys = [862272]
}
Would generate the following host file:
[gamma]
192.81.216.231
[gamma.0]
192.81.216.231
[type_digitalocean_droplet]
192.81.216.231
198.211.97.15
[zeta]
198.211.97.15
[zeta.0]
198.211.97.15
This output can be fed to Ansible to provision remotes servers.

Added the inventory option to produce an output similar to Ansible host file

---

cli.go
fixtures/example.tfstate
fixtures/playbook.yml
output.go
parser.go
parser_test.go

Outputs specified in the Terraform file are passed to the Ansible dynamic inventory JSON accessible to all hosts.

Showing Terraform outputs as "global" variables

---

HomebrewFormula/terraform-inventory.rb
README.md

Make this repository work with `brew tap` and use SHA-256 for checksum,
as SHA-1 support is deprecated.

Improve Homebrew installation support

---

parser.go
parser_test.go

I'm not sure if this is a 0.7.0 change, but the format of the `outputs` object in terraform state file change to the following:
"outputs": {
"datacenter": {
"sensitive": false,
"type": "string",
"value": "mydc"
}
}

New `outputs` format in tfstate

---

cli.go
output.go
parser.go
parser_test.go

not sure if this is new in 0.7, but non-string outputs are allowed.  Without this fix, I get 
```
panic: interface conversion: interface is []interface {}, not string
goroutine 1 [running]:
panic(0x1020e0, 0xc420498e00)
/Users/isao/.gimme/versions/go1.7.darwin.amd64/src/runtime/panic.go:500 +0x1a1
main.(*state).outputs(0xc4200722c0, 0xc420357bc0, 0xc4202cdd00, 0xc4202cdd50)
/Users/isao/dev/src/github.com/adammck/terraform-inventory/parser.go:41 +0x3b0
main.gatherResources(0xc4200722c0, 0xc4a44)
/Users/isao/dev/src/github.com/adammck/terraform-inventory/cli.go:23 +0x3a3
main.cmdList(0x19f4c0, 0xc420098008, 0x19f4c0, 0xc420098010, 0xc4200722c0, 0x0)
/Users/isao/dev/src/github.com/adammck/terraform-inventory/cli.go:33 +0x2b
main.main() …
```

allow for non-string outputs

---

cli.go
parser_test.go

I first noticed that I was unable to run `terraform-inventory --list` without first exporting `TF_STATE=.terraform/terraform.tfstate` and as per the README it appears as though having to export TF_STATE was optional. Second, I noticed that when running `ansible-playbook` with the `--list-hosts` flag `ansible-playbook` would say there were no hosts found. When I removed `--list-hosts` it detected the host that the playbook should run against.
I then ran `git bisect` to track down the problem. And I was led to this commit https://github.com/adammck/terraform-inventory/commit/6ead28eee6fce717940d217b7d7705ea4104845f. I noticed that in cli.go this change added an "all" group to the Ansible inventory, so I went to check the Ansible docs regarding the format expected from a script. …

Create all group as per Ansible inventory script conventions

---

cli.go

Initializes all_group to be an empty array

---

parser_test.go
resource.go

`terraform-inventory` currently creates groups like the following...
`{"%_5":["10.95.12.224"],"%_6":["53.81.162.94"], ...`
This ensures these groups do not get created.

Stop creating groups for tfstate attribute counts

---

parser_test.go
resource.go

hello, I've added integration for openstack way of calling tags

added openstack metadata integration

---

README.md
input.go
input_test.go
main.go

This PR adds support for
- TF_STATE, can be a path to a state file or a path to a terraform root directory
- If it is a directory it runs `terraform state pull` which manages both local and remote state as documented [here](https://www.terraform.io/docs/commands/state/pull.html).
I had a look at [#PR59](https://github.com/adammck/terraform-inventory/pull/59) but it I did not like the fact that it only support s3 and talked directly to it

add support for remote state in version 0.9

---

parser_test.go
resource.go

I needed support for Exoscale. They are using Cloudstack as platform, but we use their own terraform plugin that is not yet supported (https://github.com/exoscale/terraform-provider-exoscale).
This small patch is sufficient to build an inventory from terraform's tftate file produced with this plugin.

Added support for Exoscale.

---

cli.go

When using a static inventory that declares new hosts alongside a
dynamic inventory provided by this utility, ansible will call the
dynamic inventory with `--host <host>` to merge in additional vars
that may have been provided by the dynamic inventory.
The default behaviour of *terraform-inventory* is to output an error
message when an unknown host is encountered, breaking this
functionality.
The correct behaviour is to return an empty hash implying there are
no additional vars for this host.

Return an empty hash for unknown hosts

---

cli.go
parser_test.go

I receive a error when I try to use list in output variables: 
```
[all:vars]
panic: interface conversion: interface {} is []interface {}, not string
goroutine 1 [running]:
main.cmdInventory(0x11d35c0, 0xc42000c018, 0x11d35c0, 0xc42000c020, 0xc42000a0e0, 0x0)
/Users/me/go/src/github.com/adammck/terraform-inventory/cli.go:77 +0x65a
main.main()
/Users/me/go/src/github.com/adammck/terraform-inventory/main.go:100 +0x4be
```

Fix non-string vars in --inventory output

---

resource.go

Hi, there.
Just to have a clean output.
Thanks
Jacopo

Skip % when parsing OpenStack metadata

---

resource.go

Scaleway servers should be reachable through ipv6 if they don't have a
public_ip attribute.

Add public_ipv6 to keyNames

---

parser_test.go
resource.go

I use terraform with VSphere provider.
```
$ terraform version
Terraform v0.11.1
+ provider.vsphere v1.1.1
```
With terraform-inventory v0.7-pre and my tfstate file, the inventory is empty :
```
$ terraform-inventory --list terraform.tfstate
{"all":{"hosts":null,"vars":{}}}
```
In my terraform.tfstate file, the ip address can be found  :
```
"default_ip_address": "x.x.x.x",
```

Add provider.vsphere ip location

---

README.md
resource.go

Also ordered providers in README alphabetically to be user friendly.
The ip address field structure is the same as it is for the VMWare provider.

Add note that the docker provider is supported

---

cli.go
parser.go
parser_test.go
resource.go

I'm using terraform with VSphere provider.
```
$ terraform version
Terraform v0.11.1
+ provider.vsphere v1.1.1
```
And I use tags : https://www.terraform.io/docs/providers/vsphere/d/tag.html
In my terraform.tfstate file the tag names are not directly in the resources.
```
"vsphere_virtual_machine.twelve": {
"type": "vsphere_virtual_machine",
"primary": {
"id": "422cfa4a-c6bb-3405-0335-2d9b2034405f",
"attributes": {
"default_ip_address": "10.20.30.50",
"tags.#": "1",
"tags.1357913579": "urn:vmomi:InventoryServiceTag:00000000-0001-4957-81fa-1234567890ab:GLOBAL"
}
}
},
"data.vsphere_tag.testTag1": {
"type": "vsphere_tag",
"primary": {
"id": "urn:vmomi:InventoryServiceTag:00000000-0001-4957-81fa-1234567890ab:GLOBAL",
"attributes": {
"name": "testTag1"
}
}
}
```                
To solve this, …

VSphere tags in inventory

---

parser_test.go
resource.go

The idea is to use [aws_spot_instance_request](https://www.terraform.io/docs/providers/aws/r/spot_instance_request.html) terraform resources, the same way as we do for `aws_instance` resources.
For instance, this spot request:
```tf
resource "aws_spot_instance_request" "cheap_worker" {
ami                  = "ami-1234"
key_name             = "cheap-worker-ssh-key"
security_groups      = ["cheap-worker-security-group"]
wait_for_fulfillment = true
spot_type            = "one-time"
instance_type        = "t3.medium"
tags {
Role = "cheap-worker"
}
}
```
Will match later in ansible-playbook using the defined Role:
```yaml
---
- hosts: role_cheap-worker
remote_user: ubuntu
become: yes
become_user: root
tasks:
- name: install apps
apt: name=cowsay update_cache=yes
```

Add support for AWS spot instance

---

README.md
resource.go

This adds resources from the nutanix terraform provider.

Add resources from nutanix terraform provider

---

README.md
parser_test.go
resource.go

This quickly adds support for the Linode terraform provider, using existing keys and settings.
The only change required was to slightly re-order the keys in the resources. Linode uses both `ip_address` and `private_ip` - which was returning true by default. An extension to this may be to validate the correct key against a matching regex when returning, so that it only returns IPs.

Add Linode support

---

parser_test.go
resource.go

I updated the test object, the one added in #70 seems to be from an old format. Exoscale now provides a `ip_address` field like others providers. I think `networks` is still used for private network only resources, so I didn't remove it.

Added tags support for Exoscale

---

README.md
parser_test.go
resource.go

Includes tests and support for tags when using the [OpenTelekomCloud provider](https://www.terraform.io/docs/providers/opentelekomcloud/index.html).

add tests and tag support for OpenTelekomCloud

---

.travis.yml
cli.go
main.go
output.go
parser.go
parser_test.go
parser_test.go.example.tfstate
resource.go

Solves https://github.com/adammck/terraform-inventory/issues/113 by implementing basic support for the output of Terraform 0.12's `terraform show -json`. I introduced new JSON-to-struct mappings for 0.12, but kept all old code to remain compatible with old Terraform versions (99% of people probably still use 0.11 right now). Internally, new-style resources are mapped to the existing struct's so almost no code apart from the parser needed any change.

Support Terraform 0.12 state format

---

parser.go
parser_test.go

This fixes the tag parsing for vsphere that broke with 0.12 (as mentioned in https://github.com/adammck/terraform-inventory/pull/114#issuecomment-503543438), by correctly parsing attributes that are lists.
It also changes the behavior a bit to closer match how the AWS tag parsing works:
All tags in vsphere has a category, so we now name the resulting groups `{tag-category}_{tag-name}` rather then just the tag name, which is pretty much equivalent to tag names and values in AWS. I think this makes more sense then the current behavior, since you can have multiple tags of the same name, in different categories.

Fix tag parsing for vsphere with terraform 0.12

---

cli.go
parser_test.go

Starting with Ansible 2.8 dots (.) are no longer allowed in ansible groups: https://docs.ansible.com/ansible/latest/reference_appendices/config.html#transform-invalid-group-chars.
This patch fixes that problem by renaming host counts to use `_<count>` instead of `.<count>`.
Tests were fixed (and passes) but fixtures/ were left untouched.

Fixed the creation of groups with invalid characters (fixes #120)

---

.travis.yml
cli.go
parser.go
parser_test.go
resource.go

Resources created with `for_each` can have string-typed indexes:
```
resource "aws_route53_record" "subdomains" {
for_each = toset(["a.domain.de", "b.domain.de", "def.domain.com"])
[...]
}
```
Which currently leads to:
```
Error reading tfstate file: 0.12 format error: json: cannot unmarshal string into Go struct field resourceStateTerraform0dot12.index of type int; pre-0.12 format error: <nil> (nil error means no content/modules found in the respective format)
```
This PR fixes that and adds a test to ensure computing resources get parsed correctly in such a case.

Fix parsing `index` field in case of non-numeric string (as allowed in `for_each` construct), fix sorting

---

parser_test.go
parser_test.go.example.tfstate
resource.go

In recent versions of the AWS Terraform provider, it is possible to attach default tags to every resource. Those tags aren't stored in the `tags` field in the Terraform state but as a special field `tags_all`. 
So this PR accepts tags for AWS resources from both fields to also export tags defined as default tags.

Support default tags for the AWS Terraform provider.

---

resource.go

Cherryservers provider includes both private_ip & primary_ip attributes for servers. Make sure the latter is preferred when building an inventory.

Add (proper) support for the Cherry servers provider

---

parser_test.go
resource.go

First stab at adding Openstack instance tag support

openstack instance tag support
